project_id = "tczuttsjfttqvcmdawbo"

[functions.generate-blog-post]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.rss]
verify_jwt = false

[functions.get-analytics]
verify_jwt = false
